// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2Y22VP3s41sTRycJNIWQA4AOGUSNQeo',
    appId: '1:475241660611:web:a4f07874e6517a50f16276',
    messagingSenderId: '475241660611',
    projectId: 'revisable-46563',
    authDomain: 'revisable-46563.firebaseapp.com',
    storageBucket: 'revisable-46563.appspot.com',
    measurementId: 'G-16G2JN0YQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWTX0DhBpk6a4f_SXSyQXabjwuQscuCQ',
    appId: '1:475241660611:android:c314420c007dbd08f16276',
    messagingSenderId: '475241660611',
    projectId: 'revisable-46563',
    storageBucket: 'revisable-46563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvrg3AicNs65ZTeaAkNIjuQA3WDs-sSE',
    appId: '1:475241660611:ios:73152ebc846d955ef16276',
    messagingSenderId: '475241660611',
    projectId: 'revisable-46563',
    storageBucket: 'revisable-46563.appspot.com',
    androidClientId: '475241660611-d44mdhpvje34k00u832s1t25uq9hq2k2.apps.googleusercontent.com',
    iosClientId: '475241660611-8v7o05skeh5o5hls22fvo5882etta6vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvrg3AicNs65ZTeaAkNIjuQA3WDs-sSE',
    appId: '1:475241660611:ios:73152ebc846d955ef16276',
    messagingSenderId: '475241660611',
    projectId: 'revisable-46563',
    storageBucket: 'revisable-46563.appspot.com',
    androidClientId: '475241660611-d44mdhpvje34k00u832s1t25uq9hq2k2.apps.googleusercontent.com',
    iosClientId: '475241660611-8v7o05skeh5o5hls22fvo5882etta6vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
